name: Build EXE

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate release notes
        run: |
          npx auto-changelog-plus --starting-version ${{ github.ref_name }}
          sed -i '1,4d' CHANGELOG.md

      - name: Upload changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: CHANGELOG.md

  build:
    runs-on: windows-latest
    needs: changelog

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download changelog
        uses: actions/download-artifact@v4
        with:
          name: changelog

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install @yao-pkg/pkg
        run: npm install -g @yao-pkg/pkg

      - name: Build EXE
        run: pkg .

      - name: Rename EXE
        run: mv dist\miditap.exe dist\MIDITap-${{ github.ref_name }}.exe

      - name: Package zip
        run: |
          mkdir release
          copy dist\MIDITap-${{ github.ref_name }}.exe release\
          mkdir release\config
          copy config\mapping.json release\config\
          cd release
          Compress-Archive -Path * -DestinationPath ..\MIDITap-${{ github.ref_name }}.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: MIDITap-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
