name: Build EXE

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate release notes
        run: |
          npx auto-changelog-plus --starting-version ${{ github.ref_name }}
          sed -i '1,4d' CHANGELOG.md

      - name: Upload changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: CHANGELOG.md

  build:
    runs-on: windows-2022
    needs: changelog

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download changelog
        uses: actions/download-artifact@v4
        with:
          name: changelog

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install @neutralinojs/neu
        run: npm install -g @neutralinojs/neu

      - name: Download NeutralinoJS runtime
        run: neu update

      - name: Build
        run: neu build

      - name: Package Windows x64
        run: |
          mkdir pkg\win_x64
          copy dist\MIDITap\MIDITap-win_x64.exe pkg\win_x64\MIDITap.exe
          copy dist\MIDITap\resources.neu pkg\win_x64\
          copy package.json pkg\win_x64\
          xcopy /E /I dist\MIDITap\extensions pkg\win_x64\extensions
          xcopy /E /I libs pkg\win_x64\libs
          xcopy /E /I node_modules pkg\win_x64\node_modules
          Compress-Archive -Path pkg\win_x64\* -DestinationPath MIDITap-${{ github.ref_name }}-win_x64.zip

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: MIDITap-${{ github.ref_name }}-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
